### ISSUE TITLE
Loading the model

### ISSUE THREAD

**Issue by ainteligencia** [Shayan2002Saha/Llama2_E-commerce_Chatbot#1]
hello!

hello how are you. i am replicating your exercise and i get this error.
thank you for your help.

model_name = "TinyPixel/Llama-2-7B-bf16-sharded"

# Configuring the bitsandbytes for the model
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,       # for adding a second quantization after the first
    bnb_4bit_quant_type="nf4",            # setting the data type of 4-bit quantization
    bnb_4bit_compute_dtype=torch.float16, # setting the data type in which the computation will occur
)

# Loading the model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    trust_remote_code=True,
    device_map="auto"                     # loading the model is handled by accelerate
)

# Loading the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token # padding tokens are used to
                                          # make the arrays of token the same size for batching

------------------error

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-32614015f947>](https://localhost:8080/#) in <cell line: 12>()
     10 
     11 # Loading the model
---> 12 model = AutoModelForCausalLM.from_pretrained(
     13     model_name,
     14     quantization_config=bnb_config,

1 frames
[/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   2840                 }
   2841                 if "cpu" in device_map_without_lm_head.values() or "disk" in device_map_without_lm_head.values():
-> 2842                     raise ValueError(
   2843                         """
   2844                         Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit

ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

**Comment by Shayan2002Saha** [comment]
Hi, I'm doing good thanks for asking. It seems like there is not enough GPU or CPU to load the model. Could you please tell if you are running this locally or on Google Colab. If you are running on Google Colab, make sure you are using a GPU runtime.

**Comment by ainteligencia** [comment]
thank you for responding so quickly.
I am running it in google colab and the Change runtime type, Hardware accelerator is selected the T4 GPU.

**Comment by Shayan2002Saha** [comment]
I ran it on my end in Google Colab just now and there was no error. Could you please delete the runtime and run the notebook again ?  It seems like a problem on Colab's end.

**Comment by ainteligencia** [comment]
Again thank you very much for your quick response.
I made your recommendation, but the problem continues. I attach a picture of the error and the GPU configuration.


![image](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/108409397/11dd809b-89f9-4599-a26a-442a0e877e9e)

![image](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/108409397/3a7d7cab-b5cb-461a-9d16-11134dd5ae8f)

**Comment by Shayan2002Saha** [comment]
Okay, could you please share your notebook link here so that I can check ? Because if the code is same then there is no reason for  the error as in my end its perfectly running.

**Comment by ainteligencia** [comment]
https://drive.google.com/drive/folders/1YZBGKjOL5O48j1jA5iPQZw_l0DyU4Z38?usp=drive_link

**Comment by Shayan2002Saha** [comment]
You need to give access to the notebook. Share it after setting general access to "anyone with link".

**Comment by ainteligencia** [comment]
done
https://drive.google.com/drive/folders/1YZBGKjOL5O48j1jA5iPQZw_l0DyU4Z38?usp=sharing

**Comment by Shayan2002Saha** [comment]
Okay...I tested it on your notebook and there was no error.
So...what I found out that this error is coming due to the CUDA version of the GPU that Google Colab is allotting for you.

 I have added a new cell to check the CUDA version after you connect the Colab notebbok. Run this cell and send me the pic of the output. 
![Capture1](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/74817087/0650a35a-4dde-49ed-9c4a-a9f702b37727)


Also run the cell below and send a pic of the output. There was a warning before but in my case there is no warning.
![Capture2](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/74817087/318ef4f5-ce9d-44e7-813f-cb133b426e87)

**Comment by ainteligencia** [comment]
thank you for your support.
I have to tell you that I ran the code you were reviewing again and it worked without any problem. it did not bring up any of the messages again and I attach evidence.

![image](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/108409397/876c4451-1fc1-49f1-98f4-6e80f8959262)

![image](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/108409397/ba49d47b-51c5-4114-ac68-8677516b34a6)

![image](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/108409397/fdcaf4a2-9dbb-4811-a4dc-343260332bd9)

but I'm still wondering why it wasn't working before I shared it with you?

**Comment by Shayan2002Saha** [comment]
Yeah I was wondering that as well. Maybe it depends on the hardware that Google Colab provides. Before, the GPU may not have the correct version needed to load the model properly. That is the problem of using these cloud platforms...you never know which system they will give you., so you have reconnect again and again if this type of problem occurs until you get the right machine.
Again thats just my thought, I still don't know the exact reason. Anyways, feel free to inform me if you face any other issues. Cheers.

**Comment by ainteligencia** [comment]
Hello shayan I tell you that after a while I get the same error again and the specifications have not changed.
but if it must be something from google colab.

![image](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/108409397/490fe64b-6736-4cc8-8b5d-3498963fc7b7)


![image](https://github.com/Shayan2002Saha/Llama2_E-commerce_Chatbot/assets/108409397/08f58784-03f9-41df-9ede-c9f42a055aa5)

**Comment by Shayan2002Saha** [comment]
I would suggest if you have other Google account, try to run Colab with that. This might be a problem from their side, I'm not sure.

**Comment by ainteligencia** [comment]
thank you very much for your quick reply and I think that with this message we have closed the case. I am using the free option and after running several times different sessions google coba lowers my gpu utility just letting me use as little as possible of its platform. that is where the error comes out. 
conclusion: the error is as you say, it does not have enough GPU to process it.

Thanks
